# Site settings
title: Lucas Taliberti's CV 
description: Lucas Taliberti's CV
favicon: /assets/img/avatar.jpg
baseurl: "" #https://ddbullfrog.github.io/resumecard
url: / #https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-84144373-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Lucas Taliberti de Sousa
  title: ERP Systems Consultant and Web Developer
  address: SÃ£o Paulo, Brasil
  email: lucastaliberti#gmail.com
  link: http://lucastaliberti.github.io/
  weibo:
  github: lucastaliberti
  linkedin: lucastaliberti
  twitter: 
  gavatar: /assets/img/avatar.jpg
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Portuguese
      proficiency: Native
    - language2:
      name: English
      proficiency: Advanced
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
